### ISSUE TITLE
Hello. I would like to ask how to download  subtitles and default audio？

### ISSUE THREAD

**Issue by daliali2088** [stefanodvx/flixcrack#1]
Title

**Comment by stefanodvx** [comment]
hi, wdym by default audio?

**Comment by daliali2088** [comment]
> hi, wdym by default audio?

original audio, no need to set manually

**Comment by stefanodvx** [comment]
will add support for it in future

**Comment by daliali2088** [comment]
> 将来会添加对它的支持



> will add support for it in future

thanks
