### ISSUE TITLE
Request!

### ISSUE THREAD

**Issue by Palyer321** [stefanodvx/flixcrack#13]
Can you please add support for proxy.

**Comment by stefanodvx** [comment]
sure, in the next update.

**Comment by Palyer321** [comment]
> sure, in the next update.

Thank you for adding support. I looked in the code and was thinking shouldn't we add proxy when requesting license? Like in [this](https://github.com/stefanodvx/flixcrack/blob/78791d10fdd16eb1a467f0eb26859683dcdc9d44/flixcrack/netflix.py#L567) line.

**Comment by stefanodvx** [comment]
https://github.com/stefanodvx/flixcrack/blob/78791d10fdd16eb1a467f0eb26859683dcdc9d44/flixcrack/netflix.py#L388
its a requests session, proxy is used for license too.
