### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by whip28** [stefanodvx/flixcrack#6]
Yes I have an android CDM L3 but I don't understand how to use your script. 
the devices folder i place it in flixcrack or in folder which has setup.py . 
same thing for my cookies file I place it in which folder. 
not too obvious they have no pywidevine and cdm and decrypt files. 
With this script you can decrypt the MPL (main profil) ?. 

Thanks

I have to create a file with this script? 

from flixcrack import NetflixClient
import asyncio

client = NetflixClient(
    email="", # Insert your email here
    password="", # Insert your password here
    device="", # Insert your CDM folder name here
    quality=1080,
    audio_language=["English"],
    language="it-IT", # Metadata language
    video_profile="high",
    quiet=False
)

async def main():
    items = client.get_viewables(81470938, episode=1)
    for item in items:
        await client.download(item["viewable_id"],
            client._file_name(
                item["title"],
                item["season"],
                item["episode"],
                "dvx"
            )
        )
asyncio.run(main())

**Comment by whip28** [comment]
Thanks, I'll give it a try.
Do you decrypt the main profil 1080p with a CDM L3 Android?

**Comment by stefanodvx** [comment]
you cant decrypt Main1080p with L3, I need the bypass for it. If you have one, you can share it. you can get High1080p tho

**Comment by whip28** [comment]
what does it take as a bypass to obtain the 1080P main profil ? 
The script that made the 1080P main profile no longer works, they are blocked at 460P and 560P High. Tried several scripts to get my none gives 1080P Main Profil without success.

**Comment by stefanodvx** [comment]
You need L1 CDM to get Main1080. You can get High1080 with L3.

**Comment by whip28** [comment]
do you know how to get an L1

**Comment by whip28** [comment]
gets this error 

[img]https://i.imgur.com/Oh3M7zn.png[/img]

[img]https://i.imgur.com/oBENm8E.png[/img]

[img]https://i.imgur.com/zodlNUH.png[/img]

**Comment by stefanodvx** [comment]
you have to put device name in "device" paramter, not the folder. So if your device is "samsung-123" put samsung-123

**Comment by whip28** [comment]
gets this error
[img]https://i.imgur.com/qTVnlQk.png[/img]

**Comment by stefanodvx** [comment]
missing a dependence, please join telegram group, explaining via issue is a pain 🙂

**Comment by whip28** [comment]
what are the good files to download they have several on the links. Why not include everything with your script?. 

thanks

## Dependencies

* <a href="https://ffmpeg.org/">FFmpeg</a>
* <a href="https://github.com/aria2/aria2">aria2</a>
* <a href="https://github.com/shaka-project/shaka-packager">Shaka Packager</a>
* <a href="https://mkvtoolnix.download/">MKVToolNix</a>

**Comment by medoo5011** [comment]
thank you so much
Now it works well with serials
I want to download all sounds and all translations
As for the movies, I haven't been successful yet
